CLOSE ALL
CLEAR
SET SYSMENU OFF
SET STATUS BAR OFF
SET EXCLUSIVE OFF
SET ESCAPE OFF
SET SAFETY OFF
SET MULTILOCKS ON
SET DELETED ON
SET CARRY OFF
SET DEFAULT TO "C:\Users\bogdan\Documents\Visual Foxpro Projects\prip1"
WAIT WINDOW "Press any key"
?"run opendata"
DO "opendata.prg"